# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_Arbeitsschritt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(384, 505)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_bezeichung = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_bezeichung.setObjectName("lineEdit_bezeichung")
        self.verticalLayout_2.addWidget(self.lineEdit_bezeichung)
        spacerItem = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_extract_parameter = QtWidgets.QCheckBox(Dialog)
        self.checkBox_extract_parameter.setChecked(True)
        self.checkBox_extract_parameter.setObjectName("checkBox_extract_parameter")
        self.gridLayout.addWidget(self.checkBox_extract_parameter, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 1)
        self.pushButton_Geometrie_Importieren = QtWidgets.QPushButton(Dialog)
        self.pushButton_Geometrie_Importieren.setObjectName("pushButton_Geometrie_Importieren")
        self.gridLayout.addWidget(self.pushButton_Geometrie_Importieren, 1, 3, 1, 1)
        self.pushButton_Schnittparameter = QtWidgets.QPushButton(Dialog)
        self.pushButton_Schnittparameter.setObjectName("pushButton_Schnittparameter")
        self.gridLayout.addWidget(self.pushButton_Schnittparameter, 4, 0, 1, 2)
        self.textBrowser_Geometrie = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_Geometrie.setMinimumSize(QtCore.QSize(0, 200))
        self.textBrowser_Geometrie.setReadOnly(False)
        self.textBrowser_Geometrie.setObjectName("textBrowser_Geometrie")
        self.gridLayout.addWidget(self.textBrowser_Geometrie, 1, 0, 3, 3)
        self.pushButton_Geometrie_anpassen = QtWidgets.QPushButton(Dialog)
        self.pushButton_Geometrie_anpassen.setObjectName("pushButton_Geometrie_anpassen")
        self.gridLayout.addWidget(self.pushButton_Geometrie_anpassen, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)
        self.doubleSpinBox_offset_x = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_offset_x.setMinimum(-100000.0)
        self.doubleSpinBox_offset_x.setMaximum(100000.0)
        self.doubleSpinBox_offset_x.setSingleStep(0.1)
        self.doubleSpinBox_offset_x.setObjectName("doubleSpinBox_offset_x")
        self.gridLayout.addWidget(self.doubleSpinBox_offset_x, 5, 2, 1, 1)
        self.doubleSpinBox_offset_y = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_offset_y.setMinimum(-100000.0)
        self.doubleSpinBox_offset_y.setMaximum(100000.0)
        self.doubleSpinBox_offset_y.setSingleStep(0.1)
        self.doubleSpinBox_offset_y.setObjectName("doubleSpinBox_offset_y")
        self.gridLayout.addWidget(self.doubleSpinBox_offset_y, 6, 2, 1, 1)
        self.doubleSpinBox_offset_phi = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_offset_phi.setMinimum(-100000.0)
        self.doubleSpinBox_offset_phi.setMaximum(100000.0)
        self.doubleSpinBox_offset_phi.setSingleStep(0.1)
        self.doubleSpinBox_offset_phi.setObjectName("doubleSpinBox_offset_phi")
        self.gridLayout.addWidget(self.doubleSpinBox_offset_phi, 7, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_Laden = QtWidgets.QPushButton(Dialog)
        self.pushButton_Laden.setObjectName("pushButton_Laden")
        self.verticalLayout.addWidget(self.pushButton_Laden)
        self.pushButton_exportieren = QtWidgets.QPushButton(Dialog)
        self.pushButton_exportieren.setObjectName("pushButton_exportieren")
        self.verticalLayout.addWidget(self.pushButton_exportieren)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Arbeitsschritte"))
        self.label_2.setText(_translate("Dialog", "Bezeichnung"))
        self.checkBox_extract_parameter.setText(_translate("Dialog", "aus Geometrie übernehmen"))
        self.pushButton_Geometrie_Importieren.setText(_translate("Dialog", "Datei wählen"))
        self.pushButton_Schnittparameter.setText(_translate("Dialog", "Schnittparameter"))
        self.pushButton_Geometrie_anpassen.setText(_translate("Dialog", "Geometrie anpassen"))
        self.label_5.setText(_translate("Dialog", "Geometrie"))
        self.label_3.setText(_translate("Dialog", "Offset X [mm]"))
        self.label_4.setText(_translate("Dialog", "Offset Y [mm]"))
        self.label_6.setText(_translate("Dialog", "Rotation [°]"))
        self.pushButton_Laden.setText(_translate("Dialog", "importieren"))
        self.pushButton_exportieren.setText(_translate("Dialog", "exportieren"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
