# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_Schnittparameter.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 664)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 610, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 160, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(210, 60, 121, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(210, 110, 111, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(210, 160, 161, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 210, 61, 16))
        self.label_9.setObjectName("label_9")
        self.spinBox_AS_PU = QtWidgets.QSpinBox(Dialog)
        self.spinBox_AS_PU.setGeometry(QtCore.QRect(210, 180, 121, 22))
        self.spinBox_AS_PU.setMinimum(1)
        self.spinBox_AS_PU.setMaximum(4)
        self.spinBox_AS_PU.setObjectName("spinBox_AS_PU")
        self.spinBox_QU = QtWidgets.QSpinBox(Dialog)
        self.spinBox_QU.setGeometry(QtCore.QRect(20, 230, 131, 22))
        self.spinBox_QU.setMinimum(1)
        self.spinBox_QU.setMaximum(3)
        self.spinBox_QU.setObjectName("spinBox_QU")
        self.comboBox_XX13_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_XX13_3.setGeometry(QtCore.QRect(20, 290, 131, 22))
        self.comboBox_XX13_3.setObjectName("comboBox_XX13_3")
        self.comboBox_XX13_3.addItem("")
        self.comboBox_XX13_3.addItem("")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(20, 270, 121, 16))
        self.label_11.setObjectName("label_11")
        self.spinBox_EinschaltdauerVacuum = QtWidgets.QSpinBox(Dialog)
        self.spinBox_EinschaltdauerVacuum.setGeometry(QtCore.QRect(160, 450, 131, 22))
        self.spinBox_EinschaltdauerVacuum.setObjectName("spinBox_EinschaltdauerVacuum")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(20, 330, 161, 16))
        self.label_12.setObjectName("label_12")
        self.spinBox_Z_Achse_delay = QtWidgets.QSpinBox(Dialog)
        self.spinBox_Z_Achse_delay.setGeometry(QtCore.QRect(20, 350, 131, 22))
        self.spinBox_Z_Achse_delay.setObjectName("spinBox_Z_Achse_delay")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(160, 430, 161, 16))
        self.label_13.setObjectName("label_13")
        self.pushButton_Laden = QtWidgets.QPushButton(Dialog)
        self.pushButton_Laden.setGeometry(QtCore.QRect(20, 590, 101, 23))
        self.pushButton_Laden.setObjectName("pushButton_Laden")
        self.pushButton_exportieren = QtWidgets.QPushButton(Dialog)
        self.pushButton_exportieren.setGeometry(QtCore.QRect(20, 620, 101, 23))
        self.pushButton_exportieren.setObjectName("pushButton_exportieren")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_bezeichung = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_bezeichung.setGeometry(QtCore.QRect(20, 30, 301, 20))
        self.lineEdit_bezeichung.setObjectName("lineEdit_bezeichung")
        self.doubleSpinBox_LL = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_LL.setGeometry(QtCore.QRect(20, 80, 131, 22))
        self.doubleSpinBox_LL.setDecimals(1)
        self.doubleSpinBox_LL.setMaximum(100.0)
        self.doubleSpinBox_LL.setObjectName("doubleSpinBox_LL")
        self.doubleSpinBox_ML = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_ML.setGeometry(QtCore.QRect(20, 130, 131, 22))
        self.doubleSpinBox_ML.setDecimals(1)
        self.doubleSpinBox_ML.setMaximum(100.0)
        self.doubleSpinBox_ML.setObjectName("doubleSpinBox_ML")
        self.spinBox_LF = QtWidgets.QSpinBox(Dialog)
        self.spinBox_LF.setGeometry(QtCore.QRect(20, 180, 131, 22))
        self.spinBox_LF.setMaximum(20000)
        self.spinBox_LF.setObjectName("spinBox_LF")
        self.doubleSpinBox_VU = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_VU.setGeometry(QtCore.QRect(210, 130, 121, 22))
        self.doubleSpinBox_VU.setDecimals(1)
        self.doubleSpinBox_VU.setMinimum(0.1)
        self.doubleSpinBox_VU.setMaximum(100.0)
        self.doubleSpinBox_VU.setObjectName("doubleSpinBox_VU")
        self.doubleSpinBox_VS = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_VS.setGeometry(QtCore.QRect(210, 80, 121, 22))
        self.doubleSpinBox_VS.setDecimals(1)
        self.doubleSpinBox_VS.setMinimum(0.1)
        self.doubleSpinBox_VS.setMaximum(100.0)
        self.doubleSpinBox_VS.setObjectName("doubleSpinBox_VS")
        self.checkBox_Z_Achse_hoch_bei_PU = QtWidgets.QCheckBox(Dialog)
        self.checkBox_Z_Achse_hoch_bei_PU.setGeometry(QtCore.QRect(20, 400, 191, 17))
        self.checkBox_Z_Achse_hoch_bei_PU.setObjectName("checkBox_Z_Achse_hoch_bei_PU")
        self.checkBox_PB2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_PB2.setGeometry(QtCore.QRect(20, 450, 81, 17))
        self.checkBox_PB2.setObjectName("checkBox_PB2")
        self.checkBox_PB4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_PB4.setGeometry(QtCore.QRect(20, 490, 121, 17))
        self.checkBox_PB4.setObjectName("checkBox_PB4")
        self.checkBox_EG = QtWidgets.QCheckBox(Dialog)
        self.checkBox_EG.setGeometry(QtCore.QRect(20, 530, 111, 17))
        self.checkBox_EG.setObjectName("checkBox_EG")
        self.spinBox_AS_PD = QtWidgets.QSpinBox(Dialog)
        self.spinBox_AS_PD.setGeometry(QtCore.QRect(210, 230, 121, 22))
        self.spinBox_AS_PD.setMinimum(1)
        self.spinBox_AS_PD.setMaximum(4)
        self.spinBox_AS_PD.setObjectName("spinBox_AS_PD")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(210, 210, 161, 16))
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Dialog)
        self.comboBox_XX13_3.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Schnittparamteter"))
        self.label_3.setText(_translate("Dialog", "LL Laser Power %"))
        self.label_4.setText(_translate("Dialog", "ML minimal Laser Power %"))
        self.label_5.setText(_translate("Dialog", "LF Laser Frequency [HZ]"))
        self.label_6.setText(_translate("Dialog", "VS Velocity select [cm/s]"))
        self.label_7.setText(_translate("Dialog", "VU Velocity UP [cm/s]"))
        self.label_8.setText(_translate("Dialog", "AS PU Acceleration select"))
        self.label_9.setText(_translate("Dialog", "QU Quality"))
        self.comboBox_XX13_3.setItemText(0, _translate("Dialog", "Unten"))
        self.comboBox_XX13_3.setItemText(1, _translate("Dialog", "Oben"))
        self.label_11.setText(_translate("Dialog", "XX13,3 Z Achse bei PD"))
        self.label_12.setText(_translate("Dialog", "Wartezeit Z Achse [1/100 s]"))
        self.label_13.setText(_translate("Dialog", "Einschaltdauer Vacuum [1/100 s]"))
        self.pushButton_Laden.setText(_translate("Dialog", "importieren"))
        self.pushButton_exportieren.setText(_translate("Dialog", "exportieren"))
        self.label_2.setText(_translate("Dialog", "Bezeichnung"))
        self.checkBox_Z_Achse_hoch_bei_PU.setText(_translate("Dialog", "Z Achse bei PU immer hochfahren"))
        self.checkBox_PB2.setText(_translate("Dialog", "PB2 Vacuum"))
        self.checkBox_PB4.setText(_translate("Dialog", "PB4 Vacuum cleaner"))
        self.checkBox_EG.setText(_translate("Dialog", "EG External Gas"))
        self.label_10.setText(_translate("Dialog", "AS PD Acceleration select"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
