# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_Schnittparameter.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 664)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 610, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 131, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_LP = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_LP.setGeometry(QtCore.QRect(20, 40, 121, 20))
        self.lineEdit_LP.setObjectName("lineEdit_LP")
        self.lineEdit_ML = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ML.setGeometry(QtCore.QRect(20, 90, 121, 20))
        self.lineEdit_ML.setObjectName("lineEdit_ML")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 121, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_LF = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_LF.setGeometry(QtCore.QRect(20, 140, 121, 20))
        self.lineEdit_LF.setObjectName("lineEdit_LF")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(210, 20, 121, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_VS = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_VS.setGeometry(QtCore.QRect(210, 40, 113, 20))
        self.lineEdit_VS.setObjectName("lineEdit_VS")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(210, 70, 111, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_VU = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_VU.setGeometry(QtCore.QRect(210, 90, 113, 20))
        self.lineEdit_VU.setObjectName("lineEdit_VU")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(210, 120, 161, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 180, 61, 16))
        self.label_9.setObjectName("label_9")
        self.spinBox_AS = QtWidgets.QSpinBox(Dialog)
        self.spinBox_AS.setGeometry(QtCore.QRect(210, 140, 111, 22))
        self.spinBox_AS.setObjectName("spinBox_AS")
        self.spinBox_QU = QtWidgets.QSpinBox(Dialog)
        self.spinBox_QU.setGeometry(QtCore.QRect(20, 200, 131, 22))
        self.spinBox_QU.setObjectName("spinBox_QU")
        self.radioButton_PB2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_PB2.setGeometry(QtCore.QRect(20, 410, 111, 17))
        self.radioButton_PB2.setChecked(False)
        self.radioButton_PB2.setObjectName("radioButton_PB2")
        self.radioButton_PB4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_PB4.setGeometry(QtCore.QRect(20, 450, 131, 17))
        self.radioButton_PB4.setChecked(False)
        self.radioButton_PB4.setAutoExclusive(False)
        self.radioButton_PB4.setObjectName("radioButton_PB4")
        self.comboBox_XX13_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_XX13_3.setGeometry(QtCore.QRect(20, 260, 131, 22))
        self.comboBox_XX13_3.setObjectName("comboBox_XX13_3")
        self.comboBox_XX13_3.addItem("")
        self.comboBox_XX13_3.addItem("")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(20, 240, 121, 16))
        self.label_11.setObjectName("label_11")
        self.spinBox_EinschaltdauerVacuum = QtWidgets.QSpinBox(Dialog)
        self.spinBox_EinschaltdauerVacuum.setGeometry(QtCore.QRect(160, 410, 131, 22))
        self.spinBox_EinschaltdauerVacuum.setObjectName("spinBox_EinschaltdauerVacuum")
        self.radioButton_Z_Achse_hoch_bei_PU = QtWidgets.QRadioButton(Dialog)
        self.radioButton_Z_Achse_hoch_bei_PU.setGeometry(QtCore.QRect(20, 350, 191, 17))
        self.radioButton_Z_Achse_hoch_bei_PU.setChecked(True)
        self.radioButton_Z_Achse_hoch_bei_PU.setAutoExclusive(False)
        self.radioButton_Z_Achse_hoch_bei_PU.setObjectName("radioButton_Z_Achse_hoch_bei_PU")
        self.radioButton_EG = QtWidgets.QRadioButton(Dialog)
        self.radioButton_EG.setGeometry(QtCore.QRect(20, 490, 131, 17))
        self.radioButton_EG.setChecked(True)
        self.radioButton_EG.setAutoExclusive(False)
        self.radioButton_EG.setObjectName("radioButton_EG")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(20, 290, 161, 16))
        self.label_12.setObjectName("label_12")
        self.spinBox_Z_Achse_delay = QtWidgets.QSpinBox(Dialog)
        self.spinBox_Z_Achse_delay.setGeometry(QtCore.QRect(20, 310, 131, 22))
        self.spinBox_Z_Achse_delay.setObjectName("spinBox_Z_Achse_delay")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(160, 390, 161, 16))
        self.label_13.setObjectName("label_13")
        self.pushButton_Laden = QtWidgets.QPushButton(Dialog)
        self.pushButton_Laden.setGeometry(QtCore.QRect(20, 590, 101, 23))
        self.pushButton_Laden.setObjectName("pushButton_Laden")
        self.pushButton_exportieren = QtWidgets.QPushButton(Dialog)
        self.pushButton_exportieren.setGeometry(QtCore.QRect(20, 620, 101, 23))
        self.pushButton_exportieren.setObjectName("pushButton_exportieren")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "LL Laser Power %"))
        self.label_4.setText(_translate("Dialog", "ML minimal Laser Power %"))
        self.label_5.setText(_translate("Dialog", "LF Laser Frequency [HZ]"))
        self.label_6.setText(_translate("Dialog", "VS Velocity select [cm/s]"))
        self.label_7.setText(_translate("Dialog", "VU Velocity UP [cm/s]"))
        self.label_8.setText(_translate("Dialog", "AS Acceleration select"))
        self.label_9.setText(_translate("Dialog", "QU Quality"))
        self.radioButton_PB2.setText(_translate("Dialog", "PB2 Vacuum"))
        self.radioButton_PB4.setText(_translate("Dialog", "PB4 Vacuum cleaner"))
        self.comboBox_XX13_3.setItemText(0, _translate("Dialog", "Unten"))
        self.comboBox_XX13_3.setItemText(1, _translate("Dialog", "Oben"))
        self.label_11.setText(_translate("Dialog", "XX13,3 Z Achse bei PD"))
        self.radioButton_Z_Achse_hoch_bei_PU.setText(_translate("Dialog", "Z Achse bei PU immer hochfahren"))
        self.radioButton_EG.setText(_translate("Dialog", "EG External Gas"))
        self.label_12.setText(_translate("Dialog", "Wartezeit Z Achse [1/100 s]"))
        self.label_13.setText(_translate("Dialog", "Einschaltdauer Vacuum [1/100 s]"))
        self.pushButton_Laden.setText(_translate("Dialog", "importieren"))
        self.pushButton_exportieren.setText(_translate("Dialog", "exportieren"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
